= NixOS with Determinate Nix for Hetzner Cloud
____
Hetzner Cloud images with NixOS and Determinate Nix.
____

http://docs.outskirtslabs.com/nixos-hetzner/next/[image:https://img.shields.io/badge/doc-outskirtslabs-orange.svg[doc]]
http://docs.outskirtslabs.com/open-source-vital-signs#static[image:https://img.shields.io/badge/status-static-blue.svg[status:
static]]

Hetzner is a price-competitive and conceptually simpler alternative to
AWS and the other hyperscalers for the small orgs and teams that
https://outskirtslabs.com[I tend to work with].

Using NixOS on Hetzner has traditionally been a bear, because Hetzner
does not provide a NixOS image nor a straightforward way to create one.
Most folks resort to using nixos-infect, nixos-anywhere to transmogrify
a debian/ubuntu instance into NixOS.

However several developments over the past year have changed the status
quo:

[arabic]
. https://github.com/apricote/hcloud-upload-image[hcloud-upload-image]
was released, a simple golang tool that takes a disk image as input and
sideffects Hetzner Cloud in such a way that it creates a Snapshot from
said image
. https://github.com/NixOS/nixpkgs/pull/375551[PR #375551] is making its
way into nixpkgs which brings in `hcloud-upload-image` as well as the
NixOS plumbing needed to produce hetzner images.
. https://flakehub.com/cache[FlakeHub Cache], available since late 2024,
makes it _blazing_ fast to copy built closures into a running system.

To be clear: I was not responsible for any of this. I'm taking advantage
of the open-source efforts of others. This repo takes these disparate
pieces and ties them together into an out-of-the-box solution for
building Hetzner Cloud NixOS images.

(and yes, even this repo is a derivative as I based it on
https://determinate.systems[Determinate Systems]'s
https://github.com/DeterminateSystems/nixos-amis[repo for AWS AMIs])

'''''

[NOTE]
====
This is a proof-of-concept repo maintained by me and not DetSys. I use
something like this in prod, so what is here works, however don't count
on me to provide the same maintenance and upkeep like DetSys does for
their official AWS AMIs.
====

This repo makes available NixOS Hetzner Cloud images containing
https://docs.determinate.systems/determinate-nix[Determinate Nix]

Images are available for these systems:

* `x86++_++64-linux`
* `aarch64-linux`

On both systems, the images have these tools installed:

* https://docs.determinate.systems/determinate-nix[Determinate Nix],
Determinate Systems' validated and secure
https://docs.determinate.systems/determinate-nix[Nix] distribution for
enterprises. This includes
https://docs.determinate.systems/determinate-nix#determinate-nixd[Determinate
Nixd], a utility that enables you to log in to
https://flakehub.com[FlakeHub] from AWS using only this command (amongst
other tasks):
+
[source,shell]
----
determinate-nixd login token --token-file <path to token>
----
+
Once logged in, your VM can access
https://docs.determinate.systems/flakehub/cache[FlakeHub Cache] and
https://docs.determinate.systems/flakehub/private-flakes[private flakes]
for your organization.
* https://docs.determinate.systems/flakehub/cli[fh], the CLI for
https://flakehub.com[FlakeHub]. You can use fh for things like
https://docs.determinate.systems/flakehub/cli#apply-nixos[applying]
NixOS configurations uploaded to
https://docs.determinate.systems/flakehub/cache[FlakeHub Cache]. Here's
an example:
+
[source,shell]
----
determinate-nixd login token --token-file <path to token>
fh apply nixos "my-org/my-flake/*#nixosConfigurations.my-nixos-configuration-output"
----

Project status:
*http://docs.outskirtslabs.com/open-source-vital-signs#static[Static]*.

== Example

For a detailed example of deploying NixOS systems to Hetzner Cloud using
these images, see our
https://github.com/outskirtslabs/nixos-hetzner-demo[nixos-hetzner-demo]
repo.

Here's a simple way to get started:

[arabic]
. https://docs.hetzner.com/cloud/api/getting-started/generating-api-token/[Generate
a Hetzner Cloud token]
. Build and upload:

[source,bash]
----
HCLOUD_TOKEN=...your hcloud token...
ARCH=x86_64-linux
HCLOUD_ARCH="x86"

# or
# ARCH=aarch64-linux
# HCLOUD_ARCH="arm"
nix build "github:outskirtslabs/nixos-hetzner#diskImages.$ARCH.hetzner" --print-build-logs

# inspect the image
ls result/*
IMAGE_PATH=$(ls result/*.img 2>/dev/null | head -1)

# upload to hetzner cloud
hcloud-upload-image upload \
    --image-path="$IMAGE_PATH" \
  --architecture="$HCLOUD_ARCH" \
  --description="nixos-hetzner image"
----

== Documentation

* http://docs.outskirtslabs.com/nixos-hetzner/next/[Docs]
* http://docs.outskirtslabs.com/nixos-hetzner/next/api[API Reference]
* https://github.com/outskirtslabs/nixos-hetzner/issues[Support via
GitHub Issues]

== Changelog

-++>++ link:./CHANGELOG.adoc[CHANGELOG.adoc]

[[license-apache-license-20]]
== License: Apache License 2.0

Copyright © 2025 Casey Link casey@outskirtslabs.com

Distributed under the
https://spdx.org/licenses/Apache-2.0.html[Apache-2.0].
